# nats.conf

# Standard TCP Port für Go
port: 4222

# HTTP Monitoring Dashboard
monitor_port: 8222

# JetStream aktivieren und Speicherort festlegen
jetstream {
    store_dir: "/data"
}

# WebSocket für das TypeScript Frontend aktivieren
websocket {
    port: 9222
    no_tls: true
}